name: Gold Price Bot

on:
  schedule:
    - cron: "*/5 * * * *" # هر ۵ دقیقه اجرا شود
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Dependencies
        run: pip install requests jdatetime tzdata beautifulsoup4

      - name: Run Python Script
        run: python main.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}

      - name: Save Last Price to GitHub
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add last_price.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "📊 Update last price" && git pull --rebase origin main && git push origin main)